# Generated by Django 3.2.13 on 2022-08-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_review_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('up', 'Up vote'), ('down', 'Up down')], default='up', max_length=200),
        ),
    ]
