# Generated by Django 3.2.13 on 2022-08-11 22:29

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_review_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='project',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reviews', to='projects.project'),
        ),
    ]
