# Generated by Django 4.0 on 2022-08-13 13:33

import DevSearch.utils.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_id_alter_review_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=DevSearch.utils.uploads.project_image_upload_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default='00c61a43', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default='00c61a43', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default='00c61a43', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
