# Generated by Django 4.0 on 2022-08-16 16:07

import DevSearch.utils.uploads
import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_skill_owner'),
        ('projects', '0013_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default/no_image.png', null=True, upload_to=DevSearch.utils.uploads.project_image_upload_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
