# Generated by Django 4.0 on 2022-08-19 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_vote_ratio_project_vote_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
