# Generated by Django 4.0 on 2022-08-19 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'base_manager_name': 'prefetch_manager'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='vote_ratio',
        ),
        migrations.RemoveField(
            model_name='project',
            name='vote_total',
        ),
    ]
