# Generated by Django 4.0 on 2022-08-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_project_vote_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
        migrations.AddField(
            model_name='project',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
