# Generated by Django 4.0 on 2022-08-20 21:19

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_project_options_project_vote_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='project',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_reviews', related_query_name='project_review', to='projects.project'),
        ),
    ]
