# Generated by Django 4.0 on 2022-08-24 08:01

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_profile_options'),
        ('projects', '0026_alter_review_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='profile_project', to='accounts.profile'),
        ),
    ]
