# Generated by Django 4.0 on 2022-08-13 16:15

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_skills_alter_skill_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='owner',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_skills', to='accounts.profile'),
        ),
    ]
