# Generated by Django 4.0 on 2022-08-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_skill_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_website',
            new_name='portfolio',
        ),
    ]
