# Generated by Django 4.0 on 2022-08-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, max_length=500, null=True, unique=True),
        ),
    ]
