# Generated by Django 4.0 on 2022-08-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['profile_project__vote_ratio', 'profile_project__vote_total', '-created']},
        ),
    ]
